config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :tasks
  resources :users

end

app/models/task.rb
class Task < ActiveRecord::Base
  after_initialize :status_default

  def status_default
    self.status ||= false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  # name
  validates :name, presence: true,
                   length: { maximum: 55 }
  # email
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 255 },
                    format: { with: EMAIL_REGEX }

  # password
  has_secure_password
  validates :password, length: { minimum: 8 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      # on successful login redirect to user profile
      log_in user
      redirect_to root_path
    else
      # error message
      flash.now[:danger] = 'Invalid email/password'
      render 'new'
    end
  end

  def destroy
    if logged_in?
      log_out
    # reset_session
      flash[:success] = 'Logged out successfully'
      redirect_to root_path
    else
      flash[:warning] = 'You were not logged in'
      redirect_to root_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find params[:id]
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    @task = Task.find params[:id]

    if @task.update(task_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find params[:id]
    @task.destroy
    flash[:success] = 'To-do deleted!'
    redirect_to tasks_path
  end

  private
    def task_params
      params.require(:task).permit(:content, :category)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save 
      flash[:success] = "Welcome!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private 
    def user_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
# Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns current logged-in user. nil if none
  def current_user
    # find by id
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if user is logged in
  def logged_in?
    !current_user.nil?
  end

  # log out current logged in user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Gerald Ng
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <%= link_to 'To do', root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to 'New', new_task_path %></li>
      </ul>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        <% else %>
          <li><%= link_to 'Sign up', new_user_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |msg_type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{msg_type}" %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug params if Rails.env.development? %>
    </div>
  </body>

</html>

app/views/shared/_error_messages.html.erb
<% if entity.errors.any? %>
  <div id="error-listing">
    <div class="alert alert-danger">
      This page contains <%= pluralize entity.errors.count, 'error' %>
      <ul>
        <% entity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @task do |f| %>
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form_control' %>

      <%= f.label :category %>
      <%= f.text_field :category, class: 'form_control' %>

      <%= f.submit 'Make task', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Edit your to-do</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>All to-dos</h1>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <% @tasks.each do |task| %>
    <div class="task done-<%= task.status %>">
      <%= content_tag :p, task.content %>
      <%= content_tag :small, task.category, class: 'category' %>
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-success">
          <%= link_to 'Edit', edit_task_path(task) %>
        </button>
        <button type="button" class="btn btn-danger">
          <%= link_to 'Delete', task, method: :delete, 
                                      data: { confirm: 'Are you sure?' } %>
        </button>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New to-do</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/error_messages', entity: @task %>
    <%= render 'form' %>
  </div>
</div>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form_control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form_control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form_control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form_control' %>
    
      <%= f.submit 'Sign up', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/error_messages', entity: @user %>
    <%= render 'form' %>
  </div>
</div>